// Generated by tools/gen_assets.py - do not edit.
#ifndef ASSETS_H
#define ASSETS_H

#include <stdint.h>

#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:!->+=.\',%/"
#define FONT_NCHARS 48
#define FRAME_TILE 288
#define BAR_TILE(n, gold) (296 + (gold) * 9 + (n))   // progress bar, n of 8 pixels full
#define BIGDIGIT_TILE(d) (314 + (d) * 4)        // 16x16 digit: TL, TR, BL, BR
#define NUM_BOARDS 3

// sprite tiles (32-byte units) and palette banks
#define TILE_NOBBLE 0
#define TILE_NOBBLE_BLINK 4
#define TILE_NOBBLE_BIG 8
#define TILE_NOBBLE_BIG_BLINK 12
#define TILE_PEG 16           // 32x32 disc template
#define TILE_SOCKET 32     // 32x32 ring for an empty slot
#define TILE_DOT 48
#define TILE_SPARK 52
#define TILE_LASER_WARN 56  // 32x8
#define TILE_LASER 60        // 32x8
#define TILE_WIND 64          // 16x8
#define TILE_PAUSE 68
#define TILE_ICON(i) (72 + (i) * 4)
#define TILE_PERK(i) (116 + (i) * 4)
#define TILE_BIGICON(i) (148 + (i) * 16)
#define TILE_BIGPERK(i) (324 + (i) * 16)
#define TILE_FACE(f) (452 + (f) * 64)   // 64x64: happy, blink, wow, worry
#define TILE_HEART 708
#define TILE_HEART_EMPTY 712
#define TILE_COIN 716
#define TILE_FREE 720        // first unused sprite tile
#define PEG_TILES 16
#define POPUP_TILES 8
#define NUM_POPUPS 6
#define PAL_NOBBLE 0
#define PAL_TIER(t) (1 + (t))                   // peg colour by value tier
#define NUM_TIERS 9
#define PAL_FLASH 10
#define PAL_ICON 11
#define PAL_ICON_FLASH 12
#define PAL_ARMOR 13
#define PAL_FX 14
#define PAL_UI 15

extern const uint16_t font_pal[16];
extern const uint16_t obj_pal[256];
extern const uint32_t obj_tiles[5760];
extern const uint32_t font_tiles[2832];
extern const uint8_t glyphs5x7[10][7];                // digit bitmaps, bit 4 = left column

#endif
