// Generated by tools/gen_assets.py - do not edit.
#ifndef ASSETS_H
#define ASSETS_H

#include <stdint.h>

#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:!->+=.\',"
#define FONT_NCHARS 46
#define FRAME_TILE 184
#define NUM_BOARDS 3
#define BG_FIRST_COLOR 32
#define BG_IMG_WORDS 9600

// sprite tiles and palette banks
#define TILE_NUBBY 0
#define TILE_NUBBY_BLINK 1
#define TILE_PEG 2
#define TILE_BUMPER 3
#define TILE_ICON(i) (7 + (i) * 4)
#define PAL_NUBBY 0
#define PAL_PEG(type, lit) (1 + (type) * 2 + (lit))   // type: plus, mult, coin, bumper
#define PAL_ICON 9

extern const uint16_t font_pal[16];
extern const uint16_t obj_pal[160];
extern const uint16_t title_pal[256];
extern const uint32_t title_tiles[BG_IMG_WORDS];
extern const uint16_t *const board_pal[NUM_BOARDS];
extern const uint32_t *const board_tiles[NUM_BOARDS];
extern const uint32_t obj_tiles[312];
extern const uint32_t font_tiles[1536];

#endif
